MLX90615 implementation
R2D2-2019/temperature_sensor pull request #2
Opened 2019-05-21 15:56 UTC by MarcDirven

MLX90615 fully working.

2019-05-21 18:17 UTC, YouriMulder requested changes

2019-05-21 18:17 UTC, YouriMulder commented on code/headers/mlx90615.hpp
> +        enum : uint8_t {
Why did you chose to use a plain enum instead of enum class?

Enum class has two adventages: type safety and you can use the same name for a value in two different enums classes.

2019-05-21 18:17 UTC, YouriMulder commented on code/headers/mlx90615.hpp
> +        constexpr static float SCALE = 0.02f;
Is a float really needed here? Floats take longer to process and makes the compiled code much bigger.

2019-05-21 18:17 UTC, YouriMulder commented on code/headers/mlx90615.hpp
> +        constexpr static float KELVIN = 273.15f;
Is a float really needed here? Floats take longer to process and makes the compiled code much bigger.

2019-05-21 18:17 UTC, YouriMulder commented on code/headers/mlx90615.hpp
> +        float get_object_temperature();
What kind of value does it return?

Degrees Celcius?
Degrees Farenheid?
Degrees Kelvin?
Or something else?

2019-05-21 18:17 UTC, YouriMulder commented on code/headers/mlx90615.hpp
> +        float get_ambient_temperature();
What kind of value does it return?

Degrees Celcius?
Degrees Farenheid?
Degrees Kelvin?
Or something else?

2019-05-21 18:17 UTC, YouriMulder commented on code/headers/temperature_module.hpp
> +                    static_cast<int16_t>(mlx.get_ambient_temperature() * 10),
Why is a multiply by 10 needed?
Shouldn't this always happen and therefore should be calculated in the get_ambient_temperature?

2019-05-21 18:17 UTC, YouriMulder commented on code/headers/temperature_module.hpp
> +        }
Why is a multiply by 10 needed?
Shouldn't this always happen and therefore should be calculated in the get_object_temperature?

2019-05-21 18:17 UTC, YouriMulder commented on code/src/mlx90615.cpp
> +        // To convert a read object temperature into degrees Celsius the
I would like this comment in the hpp.

2019-05-21 18:17 UTC, YouriMulder commented on code/src/mlx90615.cpp
> +        // To convert a read object temperature into degrees Celsius the
I would like this comment in the hpp.

2019-05-21 18:22 UTC, LRstudentHU commented
To add to the `float` commentary: it should be possible to approximate the desired value by multiplying your value by 100 or 1000 and doing integer calculations. Your result could also be in the 100's.
So a temperature of 42.3 celcius would be 4230 (if the sensor is accurate to single digit, multiply by 10)

2019-05-21 18:30 UTC, MarcDirven commented on code/headers/mlx90615.hpp
> +        constexpr static float SCALE = 0.02f;
Yes, please refer to the datasheet [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwj01ejLoK3iAhWK_KQKHa-TDdEQFjAAegQIAhAC&url=https%3A%2F%2Fwww.melexis.com%2F-%2Fmedia%2Ffiles%2Fdocuments%2Fdatasheets%2Fmlx90615-datasheet-melexis.pdf&usg=AOvVaw1vkOF1fABVixZRWzUF_vr0). As the comment states this is necessairy to convert the raw data to a valid temperature.

2019-05-21 18:31 UTC, MarcDirven commented on code/headers/mlx90615.hpp
> +        constexpr static float KELVIN = 273.15f;
See [this](https://github.com/R2D2-2019/temperature_sensor/pull/2#discussion_r286165624) link

2019-05-21 18:33 UTC, MarcDirven commented on code/headers/temperature_module.hpp
> +                    static_cast<int16_t>(mlx.get_ambient_temperature() * 10),
To prevent floating point values over the CAN bus. See [this](https://github.com/R2D2-2019/internal_communication/blob/master/code/headers/frame_types.hpp) link and check the comments.

2019-05-21 18:51 UTC, MarcDirven commented on code/headers/mlx90615.hpp
> +        enum : uint8_t {
This requires explicit conversions to integers, which I, frankly, don't see any advantage in.

2019-05-21 19:25 UTC, YouriMulder commented on code/headers/mlx90615.hpp
> +        enum : uint8_t {
I personally like it because it is a type safer. The static_cast doesn't cost any runtime.
One time I had a problem with multiple enums in my class. Two values had the same name. This made me use enum classes instead.

I resolve this conversation because the plain enum is fine.

2019-05-22 06:44 UTC, YouriMulder approved these changes

2019-05-22 08:34 UTC, NathanHoekstra approved these changes
Look good, well documented 👍

2019-05-22 08:35 UTC, merged